name: Docker Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t logger .

      - name: Run container and check logs
        run: |
          mkdir -p logs
          docker run --name logger-test -d -v "$PWD/logs:/home/logs" logger
          sleep 5
          docker logs logger-test
          test -f logs/log.txt && cat logs/log.txt || echo "⚠️ No log file found"